### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by StegSchreck** [MrPowers/beavis#3]
For other developers and also companies to be able to use this nice tool in a compliant way, it would be great, if you could add a license to this repository.

How to add a license to a project on GitHub:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Helper to choose the license for your use-case: https://choosealicense.com/

**Comment by StegSchreck** [comment]
@MrPowers

**Comment by MrPowers** [comment]
@StegSchreck - Added a [LICENSE](https://github.com/MrPowers/beavis/blob/main/LICENSE.md).  Thanks for opening the issue.  Let me know if you need anything else!

**Comment by StegSchreck** [comment]
Thank you!
